name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    defaults:
      run:
        working-directory: ./iac

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: ${{ vars.WIF_SERVICE_ACCOUNT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.11.0'

    - name: Terraform Init
      env:
        GCS_BUCKET: ${{ vars.GCS_BUCKET }}
      run: |
        terraform init \
          -backend-config="bucket=${GCS_BUCKET}" \
          -backend-config="prefix=${{ vars.STATE_PREFIX }}"

    - name: Download Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan-${{ github.event.inputs.environment }}
        path: ./iac

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan-${{ github.event.inputs.environment }}
