name: 'Terraform Plan'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      TF_VAR_project_id: ${{ vars.PROJECT_ID }}
      TF_VAR_region: ${{ vars.REGION }}
      TF_VAR_environment: ${{ vars.ENVIRONMENT }}

    defaults:
      run:
        working-directory: ./iac

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: ${{ vars.WIF_SERVICE_ACCOUNT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.11.0'

    - name: Terraform Init
      env:
        GCS_BUCKET: ${{ vars.GCS_BUCKET }}
      run: |
        terraform init \
          -backend-config="bucket=${GCS_BUCKET}" \
          -backend-config="prefix=${{ vars.STATE_PREFIX }}"

    - name: Terraform Plan
      run: terraform plan -out=tfplan-${{ github.event.inputs.environment }}

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ github.event.inputs.environment }}
        path: ./iac/tfplan-${{ github.event.inputs.environment }}
        retention-days: 1
        overwrite: true
